services:
  # --- ADDED FRONTEND BACK ---
  frontend:
    container_name: flexlog-frontend
    build:
      context: .
      dockerfile: frontend/dockerfile.frontend

  backend:
    container_name: flexlog-backend
    build:
      context: .
      dockerfile: backend/dockerfile.backend
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: flexlog-db
    image: postgres:16
    env_file:
      - .env
    volumes:
      - flexlog_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  caddy:
    container_name: flexlog-proxy
    image: caddy:latest
    ports:
      - "8086:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend 

volumes:
  flexlog_data: